import { useEffect, useState, type FormEvent, type ReactNode } from 'react'
import { Bell, CheckCircle2, ChevronDown, ClipboardList, FileText, HeartPulse, LayoutDashboard, LogOut, MoreHorizontal, PawPrint, Search, Settings as SettingsIcon, ShieldCheck, Stethoscope, Users, X } from 'lucide-react'
import './App.css'
import { api, type Case, type CasePriority, type CaseStatus, type DashboardSummary, type SimilarCase, type Vet } from './api'

type NavKey = 'overview' | 'queue' | 'patients' | 'team' | 'settings'
const navItems: { key: NavKey; label: string; icon: typeof LayoutDashboard }[] = [
  { key: 'overview', label: 'Overview', icon: LayoutDashboard }, { key: 'queue', label: 'Case queue', icon: ClipboardList },
  { key: 'patients', label: 'My patients', icon: PawPrint }, { key: 'team', label: 'Team', icon: Users },
]
const demoAccounts = [
  { email: 'demo@pashurakshak.in', password: 'demo123', label: 'Dr. Riya Mehta' }, { email: 'field@pashurakshak.in', password: 'demo123', label: 'Dr. Arjun Shah' }, { email: 'admin@pashurakshak.in', password: 'demo123', label: 'Dr. Kavita Rao' },
]
const statusOptions: { value: '' | CaseStatus; label: string }[] = [
  { value: '', label: 'All cases' }, { value: 'new', label: 'New' }, { value: 'assigned', label: 'Assigned' }, { value: 'in_progress', label: 'In progress' }, { value: 'closed', label: 'Closed' },
]
const priorityLabel = (priority: CasePriority) => priority === 'red_flag' ? 'Red flag' : priority === 'high' ? 'High' : 'Normal'
const statusLabel = (status: CaseStatus) => status === 'in_progress' ? 'In progress' : status.charAt(0).toUpperCase() + status.slice(1)
function timeAgo(iso: string) { const minutes = Math.round((Date.now() - new Date(iso).getTime()) / 60000); if (minutes < 60) return `${minutes} min ago`; const hours = Math.round(minutes / 60); if (hours < 24) return `${hours} hr ago`; return `${Math.round(hours / 24)} day(s) ago` }
const initials = (name: string) => name.split(' ').map((part) => part[0]).slice(0, 2).join('')

function App() {
  const [vet, setVet] = useState<Vet | null>(null); const [loginError, setLoginError] = useState(''); const [activeNav, setActiveNav] = useState<NavKey>('overview')
  const [cases, setCases] = useState<Case[]>([]); const [summary, setSummary] = useState<DashboardSummary | null>(null); const [selectedId, setSelectedId] = useState<string | null>(null)
  const [similarCases, setSimilarCases] = useState<SimilarCase[]>([]); const [similarLoading, setSimilarLoading] = useState(false); const [query, setQuery] = useState(''); const [statusFilter, setStatusFilter] = useState<'' | CaseStatus>(''); const [showDetail, setShowDetail] = useState(false); const [loadError, setLoadError] = useState('')
  const [team, setTeam] = useState<Vet[]>([]); const [teamLoading, setTeamLoading] = useState(false)
  useEffect(() => { if (!vet) return; api.getCases(statusFilter ? { status: statusFilter } : {}).then((data) => { setCases(data); setLoadError(''); if (!selectedId && data.length) setSelectedId(data[0].id) }).catch((error: Error) => setLoadError(error.message)); api.getSummary().then(setSummary).catch(() => undefined) }, [vet, statusFilter])
  useEffect(() => { if (!selectedId) return; setSimilarLoading(true); api.getSimilarCases(selectedId).then(setSimilarCases).catch(() => setSimilarCases([])).finally(() => setSimilarLoading(false)) }, [selectedId])
  useEffect(() => { if (activeNav !== 'team' || !vet) return; setTeamLoading(true); api.getVets().then(setTeam).catch(() => setTeam([])).finally(() => setTeamLoading(false)) }, [activeNav, vet])
  const selectedCase = cases.find((item) => item.id === selectedId) ?? null; const filteredCases = cases.filter((item) => `${item.species} ${item.reported_by} ${item.village} ${item.id}`.toLowerCase().includes(query.toLowerCase())); const myCases = cases.filter((item) => item.assigned_vet_id === vet?.id); const redFlagCases = cases.filter((item) => item.priority === 'red_flag')
  const updateCase = (updated: Case) => setCases((previous) => previous.map((item) => item.id === updated.id ? updated : item))
  const openCase = (id: string) => { setSelectedId(id); setShowDetail(true); setActiveNav('queue') }
  if (!vet) return <LoginScreen onLogin={setVet} error={loginError} setError={setLoginError} />
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark"><PawPrint size={21} /></div><div><strong>Pashu<span>Rakshak</span></strong><small>VETERINARY CARE</small></div></div><nav aria-label="Main navigation">{navItems.map(({ key, label, icon: Icon }) => <a className={activeNav === key ? 'active' : ''} href={`#${key}`} key={key} onClick={(event) => { event.preventDefault(); setActiveNav(key) }}><Icon size={16} />{label}{key === 'queue' && <b>{cases.length}</b>}{key === 'patients' && myCases.length > 0 && <b>{myCases.length}</b>}</a>)}<a className={activeNav === 'settings' ? 'active' : ''} href="#settings" onClick={(event) => { event.preventDefault(); setActiveNav('settings') }}><SettingsIcon size={16} />Settings</a></nav><div className="sidebar-footer"><span className="sync-dot" />All systems synced<div className="profile"><div className="avatar">{initials(vet.name)}</div><div><strong>{vet.name}</strong><small>{vet.region.toUpperCase()}</small></div><ChevronDown size={14} /></div></div></aside><main className="main-content"><header className="topbar"><div><p className="eyebrow">SATURDAY, 05 SEPTEMBER 2026</p><h1>Good morning, {vet.name.split(' ')[1] ?? vet.name}</h1></div><div className="top-actions"><button className="icon-button" aria-label="Notifications"><Bell size={18} /><i /></button><button className="user-chip"><span className="avatar">{initials(vet.name)}</span>{vet.name}<ChevronDown size={13} /></button></div></header>{loadError && <p className="empty-state">Couldn't reach the backend: {loadError}</p>}{activeNav === 'overview' && <Overview summary={summary} cases={cases} redFlags={redFlagCases} openCase={openCase} />}{activeNav === 'queue' && <Queue cases={filteredCases} total={cases.length} selected={selectedCase} selectedId={selectedId} query={query} setQuery={setQuery} status={statusFilter} setStatus={setStatusFilter} showDetail={showDetail} setShowDetail={setShowDetail} similar={similarCases} similarLoading={similarLoading} onSelect={(id) => { setSelectedId(id); setShowDetail(true) }} onAssign={(id) => api.assignCase(id).then(updateCase)} onClose={(id) => api.closeCase(id).then(updateCase)} />}{activeNav === 'patients' && <Patients cases={myCases} openCase={openCase} />}{activeNav === 'team' && <Team team={team} loading={teamLoading} currentVet={vet.id} />}{activeNav === 'settings' && <Settings vet={vet} logout={() => setVet(null)} />}</main></div>
}

function TableRows({ cases, selectedId, onSelect }: { cases: Case[]; selectedId?: string | null; onSelect: (id: string) => void }) { return <>{cases.map((item) => <button className={`case-row ${item.priority === 'red_flag' ? 'red-row' : ''} ${item.id === selectedId ? 'selected' : ''}`} key={item.id} onClick={() => onSelect(item.id)}><span><strong>{item.species} · {item.village}</strong><small>{item.reported_by} · {item.id}</small></span><span><i className={`priority-dot ${item.priority}`} />{priorityLabel(item.priority)}</span><span className={`status status-${item.status}`}>{statusLabel(item.status)}</span><small>{timeAgo(item.created_at)}</small></button>)}</> }
function Table({ children }: { children: ReactNode }) { return <section className="queue-panel"><div className="table-labels"><span>SPECIES / REPORTER</span><span>PRIORITY</span><span>STATUS</span><span>REPORTED</span></div>{children}</section> }
function Overview({ summary, cases, redFlags, openCase }: { summary: DashboardSummary | null; cases: Case[]; redFlags: Case[]; openCase: (id: string) => void }) { return <><section className="summary-grid" aria-label="Case summary"><SummaryCard icon={<ClipboardList />} label="Open cases" value={String(summary?.total ?? cases.length)} detail="Live from /dashboard/summary" tone="teal" /><SummaryCard icon={<HeartPulse />} label="Red-flag cases" value={String(summary?.by_priority.red_flag ?? redFlags.length)} detail="Requires immediate review" tone="coral" /><SummaryCard icon={<CheckCircle2 />} label="Closed cases" value={String(summary?.by_status.closed ?? 0)} detail="Verified and completed" tone="gold" /><SummaryCard icon={<Stethoscope />} label="In progress" value={String(summary?.by_status.in_progress ?? 0)} detail="Currently being treated" tone="blue" /></section><div className="workspace-head"><div><p className="eyebrow">NEEDS ATTENTION</p><h2>Red-flag cases <span>{redFlags.length} open</span></h2></div></div><Table><TableRows cases={redFlags} onSelect={openCase} />{!redFlags.length && <p className="empty-state">No red-flag cases right now.</p>}</Table></> }
function Queue({ cases, total, selected, selectedId, query, setQuery, status, setStatus, showDetail, setShowDetail, similar, similarLoading, onSelect, onAssign, onClose }: { cases: Case[]; total: number; selected: Case | null; selectedId: string | null; query: string; setQuery: (value: string) => void; status: '' | CaseStatus; setStatus: (value: '' | CaseStatus) => void; showDetail: boolean; setShowDetail: (value: boolean) => void; similar: SimilarCase[]; similarLoading: boolean; onSelect: (id: string) => void; onAssign: (id: string) => void; onClose: (id: string) => void }) { return <><div className="workspace-head"><div><p className="eyebrow">LIVE WORKSPACE</p><h2>Case queue <span>{cases.length} of {total} shown</span></h2></div><button className="primary-button"><FileText size={14} /> New case</button></div><div className="queue-layout"><Table><div className="filters"><label className="search-box"><Search size={14} /><input aria-label="Search cases" placeholder="Search species, reporter or case ID" value={query} onChange={(event) => setQuery(event.target.value)} /></label><select aria-label="Filter cases" value={status} onChange={(event) => setStatus(event.target.value as '' | CaseStatus)}>{statusOptions.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select><button className="filter-button"><ShieldCheck size={14} /> Filters</button></div><TableRows cases={cases} selectedId={selectedId} onSelect={onSelect} />{!cases.length && <p className="empty-state">No cases match this search.</p>}</Table>{showDetail && <button className="mobile-close" aria-label="Close case details" onClick={() => setShowDetail(false)}><X size={16} /></button>}{selected && <Detail item={selected} similar={similar} loading={similarLoading} onAssign={() => onAssign(selected.id)} onClose={() => onClose(selected.id)} />}</div></> }
function Patients({ cases, openCase }: { cases: Case[]; openCase: (id: string) => void }) { return <><div className="workspace-head"><div><p className="eyebrow">ASSIGNED TO YOU</p><h2>My patients <span>{cases.length} case(s)</span></h2></div></div><Table><TableRows cases={cases} onSelect={openCase} />{!cases.length && <p className="empty-state">No cases assigned to you yet - assign one from the case queue.</p>}</Table></> }
function Team({ team, loading, currentVet }: { team: Vet[]; loading: boolean; currentVet: string }) { return <><div className="workspace-head"><div><p className="eyebrow">DIRECTORY</p><h2>Team</h2></div></div><section className="summary-grid">{loading && <p className="empty-state">Loading team...</p>}{!loading && team.map((member) => <article className="summary-card teal" key={member.id}><span className="card-icon"><Users /></span><p>{member.name}{member.id === currentVet ? ' (you)' : ''}</p><strong>{member.region}</strong><small>Veterinarian</small></article>)}{!loading && !team.length && <p className="empty-state">Couldn't load the team directory.</p>}</section></> }
function Settings({ vet, logout }: { vet: Vet; logout: () => void }) { return <><div className="workspace-head"><div><p className="eyebrow">ACCOUNT</p><h2>Settings</h2></div></div><section className="detail-panel" style={{ maxWidth: 420 }}><div className="detail-section"><h3>Profile</h3><div className="meta-grid"><div><small>Name</small><strong>{vet.name}</strong></div><div><small>Region</small><strong>{vet.region}</strong></div><div><small>Vet ID</small><strong>{vet.id}</strong></div><div><small>API base URL</small><strong>{import.meta.env.VITE_API_URL || 'http://localhost:8000'}</strong></div></div></div><div className="detail-actions"><button className="secondary-button" onClick={logout}><LogOut size={13} /> Log out</button></div></section></> }
function LoginScreen({ onLogin, error, setError }: { onLogin: (vet: Vet) => void; error: string; setError: (error: string) => void }) { const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const submit = async (event: FormEvent) => { event.preventDefault(); try { onLogin((await api.login(email, password)).vet) } catch { setError('Invalid credentials') } }; return <div className="app-shell" style={{ display: 'grid', placeItems: 'center', minHeight: '100vh' }}><form onSubmit={submit} style={{ maxWidth: 340, width: '100%', display: 'grid', gap: 12 }}><h1>PashuRakshak - Vet Login</h1><input placeholder="Email" value={email} onChange={(event) => setEmail(event.target.value)} /><input placeholder="Password" type="password" value={password} onChange={(event) => setPassword(event.target.value)} />{error && <p className="empty-state">{error}</p>}<button className="primary-button" type="submit">Log in</button><p className="eyebrow">Demo accounts (password: demo123)</p>{demoAccounts.map((account) => <button type="button" key={account.email} className="secondary-button" onClick={() => { setEmail(account.email); setPassword(account.password) }}>{account.label} - {account.email}</button>)}</form></div> }
function SummaryCard({ icon, label, value, detail, tone }: { icon: ReactNode; label: string; value: string; detail: string; tone: string }) { return <article className={`summary-card ${tone}`}><span className="card-icon">{icon}</span><p>{label}</p><strong>{value}</strong><small>{detail}</small></article> }
function Detail({ item, similar, loading, onAssign, onClose }: { item: Case; similar: SimilarCase[]; loading: boolean; onAssign: () => void; onClose: () => void }) { return <aside className="detail-panel"><div className="detail-header"><div><p className="eyebrow">SELECTED CASE</p><h2>{item.species} - {item.village}</h2><p className="case-id">{item.id} · Reported {timeAgo(item.created_at)}</p></div><button className="more-button" aria-label="More case actions"><MoreHorizontal /></button></div><div className={`alert-banner ${item.priority === 'red_flag' ? 'alert-red' : ''}`}><HeartPulse size={16} /><div><strong>{item.priority === 'red_flag' ? 'Red-flag: needs urgent attention' : item.priority === 'high' ? 'High priority review' : 'Routine review'}</strong><p>AI triage rules flagged this case as {priorityLabel(item.priority).toLowerCase()} priority.</p></div></div><section className="detail-section"><h3>Reported symptoms</h3><p className="symptom-copy">{item.symptoms}</p><div className="meta-grid"><div><small>Herd size</small><strong>{item.herd_size}</strong></div><div><small>Affected</small><strong>{item.affected_count}</strong></div><div><small>Mortality</small><strong>{item.mortality_count}</strong></div><div><small>Vaccination</small><strong>{item.vaccination_status}</strong></div><div><small>Reported by</small><strong>{item.reported_by}</strong></div><div><small>Location</small><strong>{item.village}, {item.district}</strong></div></div></section><section className="detail-section"><div className="section-heading"><h3>Similar resolved cases</h3><span>{similar.length} matches</span></div>{loading && <p className="empty-state">Searching historical cases...</p>}{!loading && similar.map((match) => <div className="similar-case" key={match.id}><b className="match-score">{Math.round(match.similarity_score * 100)}%<br />match</b><div><strong>{match.confirmed_diagnosis}</strong><p>{match.treatment_summary}</p><small>{match.outcome}</small></div></div>)}{!loading && !similar.length && <p className="empty-state">No similar historical cases found.</p>}</section><div className="detail-actions"><button className="secondary-button" onClick={onAssign} disabled={item.status !== 'new'}><Users size={13} /> Assign to me</button><button className="primary-button" onClick={onClose} disabled={item.status === 'closed'}><CheckCircle2 size={13} /> Close case</button></div></aside> }
export default App